# Generated by Django 5.0.2 on 2024-05-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_rename_author_post_user_remove_post_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='', verbose_name='picture'),
        ),
    ]
