# Generated by Django 5.0.2 on 2024-05-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_author_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
