# Generated by Django 5.0.2 on 2024-05-26 21:55

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_profile_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_directory_path),
        ),
    ]
